### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by 2sn** [evbauer/MESA-Docker#3] opened 2018-03-11 04:42 UTC
```shell
docker@db1714077444:~$ cd docker_work/
docker@db1714077444:~/docker_work$ ls
ls: cannot open directory '.': Permission denied
```

**Comment by evbauer** [comment] 2018-03-11 04:46
Thanks for posting this. I think another user had a similar issue, but I wasn't able to get enough follow up info to diagnose at the time, and I couldn't reproduce it myself.

What OS/version of the script are you using?

**Comment by evbauer** [comment] 2018-04-05 23:02
Ok, just committed some mounting fixes, so I'm hoping this is resolved now.

**Closed as completed by evbauer** 2018-04-05 23:02 UTC
